---
name: terraform-fmt
run-name: ${{github.workflow}} - ${{ github.actor }} pushed a change to ${{github.ref_name}}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "main"
permissions:
  contents: read
jobs:
  tf-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.2
      - name: Run terraform-fmt
        working-directory: ./1.6.2
        run: terraform fmt -recursive -check -diff