---
name: terraform-fmt
run-name: ${{github.workflow}} - ${{ github.actor }} pushed a change to ${{github.ref_name}}
on:
  workflow_call:
    inputs:
       terraform-version:
          required: false
          type: string
          default: 1.6.2
permissions:
  contents: read
jobs:
  tf-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform-version }}
      - name: Run terraform-fmt
        working-directory: ./1.6.2
        run: terraform fmt -recursive -check -diff